#pragma checksum "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EBEB61E20C7776A8421B7A716143EA4A65A5E48B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OmniSync.Hub.Infrastructure.Services;
using OmniSync.Hub.Presentation;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OmniSync.Hub.Presentation {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 260 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LogTextBox;
        
        #line default
        #line hidden
        
        
        #line 296 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ShutdownButton;
        
        #line default
        #line hidden
        
        
        #line 341 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ExeMappingsGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OmniSync.Hub;component/presentation/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            this.LogTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 262 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            this.LogTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.LogTextBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ShutdownButton = ((System.Windows.Controls.Button)(target));
            
            #line 298 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            this.ShutdownButton.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ShutdownButton_MouseDown);
            
            #line default
            #line hidden
            
            #line 299 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            this.ShutdownButton.PreviewMouseUp += new System.Windows.Input.MouseButtonEventHandler(this.ShutdownButton_MouseUp);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ExeMappingsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 1:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.GotFocusEvent;
            
            #line 133 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            eventSetter.Handler = new System.Windows.RoutedEventHandler(this.TextBox_GotFocus);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 5:
            
            #line 661 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            ((System.Windows.Controls.Expander)(target)).Expanded += new System.Windows.RoutedEventHandler(this.Expander_Expanded);
            
            #line default
            #line hidden
            
            #line 661 "..\..\..\..\..\OmniSync.Hub\src\OmniSync.Hub\Presentation\MainWindow.xaml"
            ((System.Windows.Controls.Expander)(target)).Collapsed += new System.Windows.RoutedEventHandler(this.Expander_Collapsed);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

