#!/usr/bin/env python3
"""
athena.cli.init - Initialize Assistant Workspace
"""

import os
from datetime import datetime
from pathlib import Path

from athena.core.defaults import OMNI_CONFIG_TEMPLATE

# --- Templates ---

CORE_IDENTITY_TEMPLATE = """# Core Identity: Omni Assistant

> **Status**: ACTIVE
> **Initialization Date**: {date}

## 1. Primary Objectives

- [ ] Maintain a dense, token-efficient map of the project structure.
- [ ] Provide expert architectural guidance across multiple stacks.
- [ ] Preserve technical narrative through rigorous session logging.

## 2. Operating Principles

- **Precision**: Adhere strictly to existing project conventions.
- **Efficiency**: Use dense summaries and compact structure maps.
- **Context**: Always verify the project state before making complex changes.
"""

START_WORKFLOW_TEMPLATE = """# Workflow: Start Session

1. Run `/omni:start` to boot the session.
2. Review the Narrative and Structure provided by the startup hook.
3. Check the Project State in `.omni/athena/context/project_state.md`.
"""

END_WORKFLOW_TEMPLATE = """# Workflow: End Session

1. Run `/omni:save` to record final achievements.
2. Run `/omni:end` to finalize the session.
3. Provide a summary of the session to the user.
"""

PROJECT_STATE_TEMPLATE = """---
created: '{date}'
last_updated: '{date}'
framework_version: v1.0.0
---

# Project State (Single Source of Truth)

## 1. System Status

- **Health**: 100%
- **Session Count**: 0
- **Last Session**: None

## 2. Recent Changes

- [{date}] Initialized Assistant workspace via `/omni:setup`.

## 3. Notes

_Add project-specific notes here._
"""

# --- IDE-Specific Templates ---

ANTIGRAVITY_RULES = """# Antigravity Agent Rules

> Auto-generated by `/omni:setup --ide antigravity`

## Boot Sequence
On `/omni:start`, run: `python -m athena`
"""

CURSOR_RULES = """# Cursor Agent Rules

> Auto-generated by `/omni:setup --ide cursor`

## Context Management
Always read `.omni/athena/framework/modules/Core_Identity.md` first.
"""

VSCODE_SETTINGS = """{
  "files.associations": {
    "*.md": "markdown"
  },
  "editor.wordWrap": "on",
  "files.exclude": {
    "**/__pycache__": true,
    "**/*.pyc": true
  },
  "markdown.preview.breaks": true
}
"""

GEMINI_RULES = """# Gemini Agent Rules

> Auto-generated by `/omni:setup --ide gemini`

## Assistant Workspace Context

This is an Assistant workspace. Key directories:
- `.omni/athena/framework/` - Core identity, read `.omni/athena/framework/modules/Core_Identity.md` first
- `.omni/athena/session_logs/` and project state
- `.omni/athena/agent/` - Workflows and automation scripts

## Session Commands

| Command | Action |
|---------|--------|
| `python -m athena` | Boot session |
| `python -m athena save "note"` | Quicksave |
| `python -m athena --end` | Close session |
| `python -m athena check` | Health check |
"""


def init_workspace(target_dir: Path = None, ide: str = None) -> bool:
    """
    Initialize an Assistant workspace with the required directory structure.

    Args:
        target_dir: Directory to initialize. Defaults to current directory.
        ide: IDE to generate config for (antigravity, cursor, vscode, gemini).

    Returns:
        True if successful, False otherwise.
    """
    root = target_dir or Path.cwd()
    root = Path(root).resolve()

    print("ASSISTANT INIT (Omni)")
    if ide:
        print(f"   IDE: {ide}")
    print("=" * 60)

    # Define structure (Consolidated into .omni/athena and .omni/projectcontext)
    directories = [
        ".omni/athena/agent/workflows",
        ".omni/athena/agent/scripts",
        ".omni/athena/agent/skills/protocols",
        ".omni/athena/framework/modules",
        ".omni/athena/session_logs",
        ".omni/athena/context/data",
        ".omni/projectcontext",
    ]

    # Create directories
    print("\nCreating directories...")
    for dir_path in directories:
        full_path = root / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        print(f"   (OK) {dir_path}/")

    # Create template files
    today = datetime.now().strftime("%Y-%m-%d")

    templates = [
        (
            ".omni/athena/framework/modules/Core_Identity.md",
            CORE_IDENTITY_TEMPLATE.format(date=today),
        ),
        (".omni/athena/agent/workflows/start.md", START_WORKFLOW_TEMPLATE),
        (".omni/athena/agent/workflows/end.md", END_WORKFLOW_TEMPLATE),
        (
            ".omni/athena/context/project_state.md",
            PROJECT_STATE_TEMPLATE.format(date=today),
        ),
        (".omni/omni_config.json", OMNI_CONFIG_TEMPLATE),
    ]

    print("\nCreating template files...")
    for file_path, content in templates:
        full_path = root / file_path
        if not full_path.exists():
            full_path.write_text(content, encoding="utf-8")
            print(f"   (OK) {file_path}")
        else:
            print(f"   (SKIP) {file_path} (already exists)")

    # IDE-specific configuration
    if ide:
        print(f"\n⚙  Creating {ide} configuration...")
        _create_ide_config(root, ide)

    # Summary
    print("\n" + "=" * 60)
    print("(OK) ASSISTANT WORKSPACE INITIALIZED")
    print("=" * 60)
    print("\nNext steps:")
    print("   1. Open this folder in your AI IDE")
    print('   2. Type "/omni:start" to boot your agent')
    print('   3. Work with your agent, then type "/omni:end" to save')
    print("\nDocs: https://github.com/winstonkoh87/Athena-Public")

    return True


def _create_ide_config(root: Path, ide: str) -> None:
    """Create IDE-specific configuration files."""

    if ide == "antigravity":
        # Antigravity uses AGENTS.md convention
        agents_path = root / "AGENTS.md"
        if not agents_path.exists():
            agents_path.write_text(ANTIGRAVITY_RULES)
            print("   (OK) AGENTS.md (Antigravity rules)")
        else:
            print("   (SKIP) AGENTS.md (already exists)")

    elif ide == "cursor":
        # Cursor uses .cursorrules
        cursor_dir = root / ".cursor"
        cursor_dir.mkdir(exist_ok=True)
        rules_path = cursor_dir / "rules.md"
        if not rules_path.exists():
            rules_path.write_text(CURSOR_RULES)
            print("   (OK) .cursor/rules.md")
        else:
            print("   (SKIP) .cursor/rules.md (already exists)")

    elif ide == "vscode":
        # VS Code uses .vscode/settings.json
        vscode_dir = root / ".vscode"
        vscode_dir.mkdir(exist_ok=True)
        settings_path = vscode_dir / "settings.json"
        if not settings_path.exists():
            settings_path.write_text(VSCODE_SETTINGS)
            print("   (OK) .vscode/settings.json")
        else:
            print("   (SKIP) .vscode/settings.json (already exists)")

    elif ide == "gemini":
        # Gemini CLI uses AGENTS.md or .gemini/
        gemini_dir = root / ".gemini"
        gemini_dir.mkdir(exist_ok=True)
        rules_path = gemini_dir / "AGENTS.md"
        if not rules_path.exists():
            rules_path.write_text(GEMINI_RULES)
            print("   (OK) .gemini/AGENTS.md")
        else:
            print("   (SKIP) .gemini/AGENTS.md (already exists)")


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    init_workspace(target)
