#!/usr/bin/env python3
"""
athena.cli.init
===============

Scaffold a new Athena workspace with directory structure and templates.
Fulfills the "5-Minute Quickstart" promise.

Usage:
    athena init .                     # Initialize in current directory
    athena init --here                # Same as above
    athena init --here --ide cursor   # Init with Cursor-specific config
    athena init my-project            # Create new project directory
"""

from datetime import datetime
from pathlib import Path


# --- Templates ---

CORE_IDENTITY_TEMPLATE = """# Core Identity

> **Created**: {date}

## Who Am I?
An adaptive AI assistant — your strategic co-pilot, not just a chatbot.

## Operating Principles

1. **Memory First**: Log everything. Context is power.
2. **Proactive**: Anticipate needs, don't just react.
3. **Honest**: Challenge flawed assumptions respectfully.
4. **Modular**: One skill = one file. No monoliths.

## Reasoning Standards

- Consider 3+ perspectives before concluding
- Label assumptions explicitly
- Prioritize signal over noise
- Ask clarifying questions when uncertain

## Success Metric

A good conversation contains mutual corrections.
- I challenge your assumptions → you evaluate
- You correct my errors → I improve
- Both get sharper
"""

START_WORKFLOW_TEMPLATE = """---
description: Boot the AI assistant with context
---

# /omni:start — Execution Script

> **Automation**: This workflow runs the Athena SDK boot sequence.

## Execution

// turbo

```bash
python -m athena
```

The boot sequence will:
1. Load Core Identity
2. Recall last session context
3. Create a new session log
4. Confirm ready status

## Manual Override (if SDK unavailable)

- [ ] Read `.omni/athena/framework/modules/Core_Identity.md`
- [ ] Find the latest session log in `.omni/athena/session_logs/`
- [ ] Create a new session log: `YYYY-MM-DD-session-XX.md`
- [ ] Output: "⚡ Ready. (Session XX started.)"
"""

END_WORKFLOW_TEMPLATE = """---
description: Close session and save learnings
---

# /omni:end — Session Close

> **Automation**: This workflow runs the Athena SDK shutdown sequence.

## Execution

// turbo

```bash
python -m athena --end
```

The shutdown sequence will:
1. Close the current session log
2. Update session status to "Closed"
3. Optionally trigger Supabase sync

## Manual Override (if SDK unavailable)

- [ ] Read all `### ⚡ Checkpoint` entries from current session log
- [ ] Fill in Key Topics, Decisions Made, Action Items
- [ ] Git add and commit the session log
- [ ] Output: "✅ Session XX closed and committed."
"""

SAVE_WORKFLOW_TEMPLATE = """---
description: Save a checkpoint to the current session
---

# /omni:save — Quicksave Checkpoint

> **Automation**: This workflow runs the Athena SDK save command.

## Execution

// turbo

```bash
python -m athena save "Brief summary of what happened"
```

The save command will append a timestamped checkpoint to the current session log.
"""


PROJECT_STATE_TEMPLATE = """---
created: '{date}'
last_updated: '{date}'
framework_version: v1.0.0
---

# Project State (Single Source of Truth)

## 1. System Status

- **Health**: 100%
- **Session Count**: 0
- **Last Session**: None

## 2. Recent Changes

- [{date}] Initialized Assistant workspace via `/omni:setup`.

## 3. Notes

_Add project-specific notes here._
"""

# --- IDE-Specific Templates ---

ANTIGRAVITY_RULES = """# Antigravity Agent Rules

> Auto-generated by `/omni:setup --ide antigravity`

## Boot Sequence
On `/omni:start`, run: `python -m athena`

## Save Sequence  
On `/omni:end`, run: `python -m athena --end`

## Quicksave
On `/omni:quicksave`, run: `python -m athena save "summary"`

## Directory Context
- `.omni/athena/framework/` — Core identity and laws
- `.omni/athena/session_logs/` — Session logs and memories  
- `.omni/athena/agent/` — Workflows and scripts
"""

CURSOR_RULES = """# Cursor Agent Rules

> Auto-generated by `/omni:setup --ide cursor`

## Context

You are an AI agent operating within an Assistant workspace.
Always check `.omni/athena/framework/modules/Core_Identity.md` for your operating principles.

## Key Directories

- `.omni/athena/framework/` — Your identity and laws (read this first)
- `.omni/athena/session_logs/` — Session logs (check for prior context)
- `.omni/athena/agent/workflows/` — Available commands (start.md, end.md, save.md)

## Boot Command

Run `python -m athena` to boot the session system, or manually read the latest session log.

## Session Discipline

1. On session start — run `/omni:start` workflow
2. During work — periodically run `/omni:save` to checkpoint
3. On session end — run `/omni:end` workflow
"""

VSCODE_SETTINGS = """{
  "files.associations": {
    "*.md": "markdown"
  },
  "editor.wordWrap": "on",
  "files.exclude": {
    "**/__pycache__": true,
    "**/*.pyc": true
  },
  "markdown.preview.breaks": true
}
"""

GEMINI_RULES = """# Gemini Agent Rules

> Auto-generated by `/omni:setup --ide gemini`

## Assistant Workspace Context

This is an Assistant workspace. Key directories:
- `.omni/athena/framework/` — Core identity, read `.omni/athena/framework/modules/Core_Identity.md` first
- `.omni/athena/session_logs/` and project state
- `.omni/athena/agent/` — Workflows and automation scripts

## Session Commands

| Command | Action |
|---------|--------|
| `python -m athena` | Boot session |
| `python -m athena save "note"` | Quicksave |
| `python -m athena --end` | Close session |
| `python -m athena check` | Health check |
"""


def init_workspace(target_dir: Path = None, ide: str = None) -> bool:
    """
    Initialize an Assistant workspace with the required directory structure.

    Args:
        target_dir: Directory to initialize. Defaults to current directory.
        ide: IDE to generate config for (antigravity, cursor, vscode, gemini).

    Returns:
        True if successful, False otherwise.
    """
    root = target_dir or Path.cwd()
    root = Path(root).resolve()

    print("🏛️  ASSISTANT INIT (Omni)")

    if ide:
        print(f"   IDE: {ide}")
    print("=" * 60)

    # Define structure (Consolidated into .omni/athena and .omni/projectcontext)
    directories = [
        ".omni/athena/agent/workflows",
        ".omni/athena/agent/scripts",
        ".omni/athena/agent/skills/protocols",
        ".omni/athena/framework/modules",
        ".omni/athena/session_logs",
        ".omni/athena/context/data",
        ".omni/projectcontext",
    ]

    # Create directories
    print("\n📁 Creating directories...")
    for dir_path in directories:
        full_path = root / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        print(f"   ✅ {dir_path}/")

    # Create template files
    today = datetime.now().strftime("%Y-%m-%d")

    templates = [
        (
            ".omni/athena/framework/modules/Core_Identity.md",
            CORE_IDENTITY_TEMPLATE.format(date=today),
        ),
        (".omni/athena/agent/workflows/start.md", START_WORKFLOW_TEMPLATE),
        (".omni/athena/agent/workflows/end.md", END_WORKFLOW_TEMPLATE),
        (".omni/athena/agent/workflows/save.md", SAVE_WORKFLOW_TEMPLATE),
        (
            ".omni/athena/context/project_state.md",
            PROJECT_STATE_TEMPLATE.format(date=today),
        ),
    ]

    print("\n📝 Creating template files...")
    for file_path, content in templates:
        full_path = root / file_path
        if not full_path.exists():
            full_path.write_text(content, encoding="utf-8")
            print(f"   ✅ {file_path}")
        else:
            print(f"   ⏭️  {file_path} (already exists)")

    # IDE-specific configuration
    if ide:
        print(f"\n⚙️  Creating {ide} configuration...")
        _create_ide_config(root, ide)

    # Summary
    print("\n" + "=" * 60)
    print("✅ ASSISTANT WORKSPACE INITIALIZED")
    print("=" * 60)
    print("\n🚀 Next steps:")
    print("   1. Open this folder in your AI IDE")
    print('   2. Type "/omni:start" to boot your agent')
    print('   3. Work with your agent, then type "/omni:end" to save')
    print("\n📚 Docs: https://github.com/winstonkoh87/Athena-Public")

    return True


def _create_ide_config(root: Path, ide: str) -> None:
    """Create IDE-specific configuration files."""

    if ide == "antigravity":
        # Antigravity uses AGENTS.md convention
        agents_path = root / "AGENTS.md"
        if not agents_path.exists():
            agents_path.write_text(ANTIGRAVITY_RULES)
            print("   ✅ AGENTS.md (Antigravity rules)")
        else:
            print("   ⏭️  AGENTS.md (already exists)")

    elif ide == "cursor":
        # Cursor uses .cursorrules
        cursor_dir = root / ".cursor"
        cursor_dir.mkdir(exist_ok=True)
        rules_path = cursor_dir / "rules.md"
        if not rules_path.exists():
            rules_path.write_text(CURSOR_RULES)
            print("   ✅ .cursor/rules.md")
        else:
            print("   ⏭️  .cursor/rules.md (already exists)")

    elif ide == "vscode":
        # VS Code uses .vscode/settings.json
        vscode_dir = root / ".vscode"
        vscode_dir.mkdir(exist_ok=True)
        settings_path = vscode_dir / "settings.json"
        if not settings_path.exists():
            settings_path.write_text(VSCODE_SETTINGS)
            print("   ✅ .vscode/settings.json")
        else:
            print("   ⏭️  .vscode/settings.json (already exists)")

    elif ide == "gemini":
        # Gemini CLI uses AGENTS.md or .gemini/
        gemini_dir = root / ".gemini"
        gemini_dir.mkdir(exist_ok=True)
        rules_path = gemini_dir / "AGENTS.md"
        if not rules_path.exists():
            rules_path.write_text(GEMINI_RULES)
            print("   ✅ .gemini/AGENTS.md")
        else:
            print("   ⏭️  .gemini/AGENTS.md (already exists)")


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    init_workspace(target)
