import zipfile
import os

def create_simple_epub(output_path):
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with zipfile.ZipFile(output_path, 'w') as epub:
        # 1. mimetype (must be first and uncompressed)
        epub.writestr('mimetype', 'application/epub+zip', compress_type=zipfile.ZIP_STORED)
        
        # 2. container.xml
        container_xml = """<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>"""
        epub.writestr('META-INF/container.xml', container_xml)
        
        # 3. content.opf
        content_opf = """<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="BookId">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>Simple Test Book</dc:title>
    <dc:language>en</dc:language>
    <dc:identifier id="BookId">test-123</dc:identifier>
    <dc:creator>Omni Assistant</dc:creator>
  </metadata>
  <manifest>
    <item id="content" href="content.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="content"/>
  </spine>
</package>"""
        epub.writestr('content.opf', content_opf)
        
        # 4. content.xhtml
        content_xhtml = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Page</title>
    <style>
        body { font-family: sans-serif; padding: 20px; color: #000; background: #fff; }
        h1 { color: #f00; }
    </style>
</head>
<body>
    <h1>EPUB Test Success!</h1>
    <p>If you can see this, the EPUB viewer is working correctly for simple files.</p>
    <p>This file was generated by the Omni Assistant to isolate rendering issues.</p>
    <hr/>
    <p>Random Fact: A group of flamingos is called a "flamboyance".</p>
</body>
</html>"""
        epub.writestr('content.xhtml', content_xhtml)

if __name__ == "__main__":
    target = "B:\\GDrive\\Books\\Books\\Misc\\test_simple.epub"
    log_target = target.replace("\\", "\\\\")
    print(f"Creating simple EPUB at: {log_target}")
    create_simple_epub(target)
    print("Done!")
